### PR TITLE
Request to get jterminal on Central.

### PR DESCRIPTION
**Pull request by hef**
Please get jterminal onto The Central Repository.  This would help resolve jterminal as a maven dependency.

I would recommend using Sonatype's free oss hosting service.  Instructions are here:
https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide

Iv'e made some updates to the pom file that might help in this process.

### CODE REVIEW

**Comment by grahamedgecombe** [comment]
I'll look at doing this asap, although shouldn't this line: https://github.com/hef/jterminal/commit/84e44aa630bf6c2d84ccf29add2c68d444c7c0ec#L0R24 refer to git://github.com/grahamedgecombe/jterminal.git?

**Comment by hef** [comment]
Yes, yes it should.  I was copying settings from one of my projects, and I missed changing that one.  The new branch head should reflect the correct value.

**Comment by hef** [comment]
I am wondering what the status of uploading the project to sonatype (or similar) is.
I havn't seen jterminal show up on http://search.maven.org/ or https://oss.sonatype.org/.

**Comment by grahamedgecombe** [comment]
I just committed & pushed another change, and have now created a 'new project' issue.

**Comment by grahamedgecombe** [comment]
JTerminal is now in the Sonatype OSS releases repository, I have commented on the ticket for them to enable central sync so hopefully it will be in Central soon.

**Comment by grahamedgecombe** [comment]
It is now in central :)

**Pull request merged**
